import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { revalidatePath } from 'next/cache';

const PORTFOLIO_SEED = [
  {
    slug: 'dashboardia',
    order: 0,
    color: '#00D4FF',
    github: 'https://github.com/miguelgargurevich/dashboardia-llm',
    live: '#',
    tech: ['Next.js 14', 'React 18', 'Node.js', 'Prisma', 'PostgreSQL', 'Supabase', 'Gemini API'],
    titleEs: 'DashboardIA LLM',
    titleEn: 'DashboardIA LLM',
    descriptionEs: 'Hub operativo de soporte técnico que centraliza knowledge base personal, gestión de recursos (PDF, Excel, video), calendario, notas y asistente IA con adjuntos. Todos los datos están aislados por usuario autenticado con Supabase, e incluye un agente Windows para ejecutar scripts PowerShell de forma remota.',
    descriptionEn: 'Operational technical-support hub that centralizes a personal knowledge base, file resources (PDF, Excel, video), calendar, notes, and an AI assistant with file attachments. All data is fully isolated per authenticated Supabase user, and includes a Windows agent for remote PowerShell script execution.',
    featuresEs: ['Aislamiento total por usuario', 'IA con adjuntos PDF/Excel/Video', 'Agente Windows PowerShell'],
    featuresEn: ['Full user-level isolation', 'AI assistant with file attachments', 'Windows PowerShell Agent'],
    imageUrl: '/projects/dashboardia.png',
  },
  {
    slug: 'invoiceapp',
    order: 1,
    color: '#8B5CF6',
    github: 'https://github.com/miguelgargurevich/invoiceapp',
    live: 'https://invoiceapp.vercel.app',
    tech: ['Next.js 14', 'Express', 'TypeScript', 'Prisma', 'PostgreSQL', 'Supabase', 'Resend'],
    titleEs: 'InvoiceApp',
    titleEn: 'InvoiceApp',
    descriptionEs: 'Plataforma de facturación y proformas para contratistas y freelancers con firma digital jurídicamente válida (token único, IP y timestamp). Incluye CRM integrado, catálogo de productos, seguimiento de obra con fotos, multi-moneda, bilingüe y envío de documentos por email vía Resend.',
    descriptionEn: 'Invoicing and proposal platform for contractors and freelancers with legally binding digital signatures (unique token, IP, and timestamp). Includes an integrated CRM, product catalog, job-site photo tracking, multi-currency, bilingual support, and document delivery via Resend.',
    featuresEs: ['Firma Digital con Token Seguro', 'CRM + Catálogo de Productos', 'Multi-moneda y Multi-idioma'],
    featuresEn: ['Legally Binding Token Signatures', 'CRM + Product Catalog', 'Multi-currency & Bilingual'],
    imageUrl: '/projects/invoiceapp.png',
  },
  {
    slug: 'house',
    order: 2,
    color: '#10B981',
    github: 'https://github.com/miguelgargurevich/house',
    live: '#',
    tech: ['React 18', 'Vite', 'Express', 'Prisma', 'PostgreSQL', 'JWT', 'Gemini API'],
    titleEs: 'House SaaS',
    titleEn: 'House SaaS',
    descriptionEs: 'SaaS multi-tenant para administración de propiedades y condominios con 5 roles diferenciados (superadmin, admin, propietario, inquilino, mantenimiento), sidebars responsivos por rol, API REST centralizada documentada con Swagger en /api-docs, copiloto Gemini AI integrado y soporte para Docker Compose en local.',
    descriptionEn: 'Multi-tenant SaaS for property and condominium management with 5 distinct roles (superadmin, admin, owner, tenant, maintenance), responsive role-based sidebars, a centralized REST API documented with Swagger at /api-docs, an integrated Gemini AI copilot, and Docker Compose support for local development.',
    featuresEs: ['5 Roles con RBAC Avanzado', 'REST API + Swagger Docs', 'Copiloto IA Gemini'],
    featuresEn: ['5 Roles with Advanced RBAC', 'REST API + Swagger Docs', 'Gemini AI Copilot'],
    imageUrl: '/projects/house.png',
  },
  {
    slug: 'jafernandez',
    order: 3,
    color: '#F59E0B',
    github: 'https://github.com/miguelgargurevich/jafernandezelectric',
    live: '#',
    tech: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Framer Motion', 'Zod'],
    titleEs: 'JA Fernandez Electric',
    titleEn: 'JA Fernandez Electric',
    descriptionEs: 'Sitio web profesional bilingüe (ES/EN) para electricista licenciado en Nassau y Suffolk County, Long Island NY. Formulario anti-spam con validación Zod y React Hook Form, sección FAQ, testimonios, animaciones con Framer Motion y SEO local optimizado para búsquedas en Long Island.',
    descriptionEn: 'Bilingual professional website (ES/EN) for a licensed electrician in Nassau and Suffolk County, Long Island NY. Anti-spam contact form with Zod and React Hook Form validation, FAQ section, testimonials, Framer Motion animations, and local SEO optimized for Long Island searches.',
    featuresEs: ['Bilingüe ES/EN con i18n custom', 'Formulario anti-spam con Zod', 'SEO Local Long Island NY'],
    featuresEn: ['Bilingual ES/EN with custom i18n', 'Anti-spam form with Zod', 'Local SEO for Long Island NY'],
    imageUrl: '/projects/jafernandez.png',
  },
  {
    slug: 'lumic',
    order: 4,
    color: '#EC4899',
    github: 'https://github.com/miguelgargurevich/lumic',
    live: '#',
    tech: ['Next.js 15', 'React 19', 'TypeScript', 'Tailwind CSS', '.NET 9', 'JWT'],
    titleEs: 'Lumic App',
    titleEn: 'Lumic App',
    descriptionEs: 'E-commerce full-stack en monorepo con frontend Next.js 15 / React 19 y backend ASP.NET Core .NET 9 en arquitectura de capas (Api, Application, Domain, Infrastructure). Autenticación JWT Bearer, OpenAPI en desarrollo y listo para despliegue en Azure Static Web Apps + App Service.',
    descriptionEn: 'Full-stack e-commerce monorepo with a Next.js 15 / React 19 frontend and a layered ASP.NET Core .NET 9 backend (Api, Application, Domain, Infrastructure). JWT Bearer authentication, OpenAPI in development, and ready for deployment on Azure Static Web Apps + App Service.',
    featuresEs: ['Monorepo Next.js + .NET 9', 'Arquitectura Hexagonal Limpia', 'Azure Static Web Apps Ready'],
    featuresEn: ['Next.js + .NET 9 Monorepo', 'Clean Layered Architecture', 'Azure Static Web Apps Ready'],
    imageUrl: '/projects/lumic.png',
  },
  {
    slug: 'portfolio',
    order: 5,
    color: '#EF4444',
    github: 'https://github.com/miguelgargurevich/miguel-gargurevich-portfolio',
    live: '#',
    tech: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'next-intl', 'Gemini AI'],
    titleEs: 'Gargurevich Digital Portfolio',
    titleEn: 'Gargurevich Digital Portfolio',
    descriptionEs: 'Mi portafolio personal construido con las últimas tecnologías web, enfocado en performance, SEO y una experiencia de usuario premium.',
    descriptionEn: 'My personal portfolio built with the latest web technologies, focusing on performance, SEO, and a premium user experience.',
    featuresEs: ['Next.js 15 + Turbopack', 'Internacionalización completa', 'Diseño Noir Premium'],
    featuresEn: ['Next.js 15 + Turbopack', 'Full Internationalization', 'Premium Noir Design'],
    imageUrl: '/projects/portfolio.png',
  },
  {
    slug: 'solucionesintegrales',
    order: 6,
    color: '#3B82F6',
    github: 'https://github.com/miguelgargurevich/solucionesintegralesjs',
    live: 'https://solucionesintegralesjs.vercel.app',
    tech: ['Next.js 14', 'React 18', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Cloudflare R2', 'Resend'],
    titleEs: 'Soluciones Integrales JS',
    titleEn: 'Soluciones Integrales JS',
    descriptionEs: 'Landing Page profesional con CMS integrado para una empresa industrial. Construida con Next.js 14, ofrece una gestión completa de servicios y proyectos, optimizada para SEO y conversiones.',
    descriptionEn: 'Professional Landing Page with an integrated CMS for an industrial company. Built with Next.js 14, it offers full service and project management, optimized for SEO and conversions.',
    featuresEs: ['CMS Personalizado', 'Optimización Industrial', 'Gestión de Proyectos R2'],
    featuresEn: ['Custom CMS', 'Industrial Optimization', 'R2 Project Management'],
    imageUrl: '/projects/solucionesintegrales.png',
  },
  {
    slug: 'pcm',
    order: 7,
    color: '#6366F1',
    github: 'https://github.com/miguelgargurevich/pcm',
    live: 'https://pcm-eight.vercel.app',
    tech: ['.NET 9', 'React 19', 'PostgreSQL', 'CQRS', 'MediatR', 'Docker', 'reCAPTCHA'],
    titleEs: 'Plataforma de Cumplimiento (PCM)',
    titleEn: 'Compliance Platform (PCM)',
    descriptionEs: 'Sistema web robusto para la gestión de compromisos y cumplimiento normativo en entidades del Estado. Implementa arquitectura CQRS con MediatR para máxima seguridad y escalabilidad.',
    descriptionEn: 'Robust web system for managing commitments and regulatory compliance in government entities. Implements CQRS architecture with MediatR for maximum security and scalability.',
    featuresEs: ['Arquitectura CQRS con MediatR', 'Gestión Gubernamental', 'Seguridad JWT + reCAPTCHA'],
    featuresEn: ['CQRS Architecture with MediatR', 'Government Management', 'JWT + reCAPTCHA Security'],
    imageUrl: '/projects/pcm.png',
  },

];

const SERVICES_SEED = [
  {
    slug: 'landing',
    icon: 'layout',
    order: 0,
    titleEs: 'Landing Pages',
    titleEn: 'Landing Pages',
    descriptionEs: 'Páginas de alta conversión optimizadas para captar leads y generar ventas.',
    descriptionEn: 'High-conversion pages optimized to capture leads and generate sales.',
    featuresEs: ['Diseño responsive', 'Alta conversión', 'SEO optimizado', 'Hosting incluido'],
    featuresEn: ['Responsive design', 'High conversion', 'SEO optimized', 'Hosting included'],
  },
  {
    slug: 'website',
    icon: 'globe',
    order: 1,
    titleEs: 'Sitios Web',
    titleEn: 'Websites',
    descriptionEs: 'Presencia digital profesional para tu marca o negocio con diseño moderno.',
    descriptionEn: 'Professional digital presence for your brand or business with modern design.',
    featuresEs: ['CMS integrado', 'Multi-idioma', 'Blog incorporado', 'Analytics'],
    featuresEn: ['Integrated CMS', 'Multi-language', 'Built-in blog', 'Analytics'],
  },
  {
    slug: 'ecommerce',
    icon: 'shopping-cart',
    order: 2,
    titleEs: 'E-commerce',
    titleEn: 'E-commerce',
    descriptionEs: 'Tiendas online modernas con gestión completa de productos y pagos.',
    descriptionEn: 'Modern online stores with complete product and payment management.',
    featuresEs: ['Carrito avanzado', 'Pagos seguros', 'Inventario', 'Dashboard'],
    featuresEn: ['Advanced cart', 'Secure payments', 'Inventory', 'Dashboard'],
  },
  {
    slug: 'webapp',
    icon: 'monitor',
    order: 3,
    titleEs: 'Apps Web',
    titleEn: 'Web Apps',
    descriptionEs: 'Aplicaciones web empresariales diseñadas para tu negocio.',
    descriptionEn: 'Enterprise web applications designed for your business.',
    featuresEs: ['PWA ready', 'Tiempo real', 'Multi-plataforma', 'Offline mode'],
    featuresEn: ['PWA ready', 'Real-time', 'Multi-platform', 'Offline mode'],
  },
  {
    slug: 'ai',
    icon: 'cpu',
    order: 4,
    titleEs: 'Integración IA',
    titleEn: 'AI Integration',
    descriptionEs: 'Inteligencia artificial integrada para automatizar procesos.',
    descriptionEn: 'Integrated artificial intelligence to automate processes.',
    featuresEs: ['Chatbots IA', 'Automatización', 'APIs LLM', 'ML Models'],
    featuresEn: ['AI Chatbots', 'Automation', 'LLM APIs', 'ML Models'],
  },
  {
    slug: 'devops',
    icon: 'server',
    order: 5,
    titleEs: 'DevOps & Cloud',
    titleEn: 'DevOps & Cloud',
    descriptionEs: 'Infraestructura escalable y automatización de despliegues.',
    descriptionEn: 'Scalable infrastructure and deployment automation.',
    featuresEs: ['CI/CD', 'Monitoreo 24/7', 'Escalabilidad', 'Backups'],
    featuresEn: ['CI/CD', '24/7 Monitoring', 'Scalability', 'Backups'],
  },
];

const OFFERS_SEED = [
  {
    planKey: 'mi-negocio-en-google',
    icon: 'zap',
    order: 0,
    popular: false,
    nameEs: 'Mi Negocio en Google',
    nameEn: 'My Business on Google',
    price: 'S/ 299',
    priceNoteEs: 'Pago único',
    priceNoteEn: 'One-time payment',
    descriptionEs: 'Aparece en Google Maps y en internet en 48 horas. Ideal si aún no tienes nada digital.',
    descriptionEn: 'Get found on Google Maps and online in 48 hours. Ideal if you do not have any digital presence yet.',
    itemsEs: [
      'Ficha de Google Maps optimizada',
      'Página de 1 sección (nombre, horario, WhatsApp, dirección)',
      'Dominio .com.pe o .pe por 1 año incluido',
      'Diseño de portada para tu perfil de Google',
      'Redirección de correo: tunegocio@midominio.pe se reenvía a tu Gmail (sin costo)',
    ],
    itemsEn: [
      'Optimized Google Maps listing',
      'Single-section page (name, hours, WhatsApp, address)',
      '.com.pe or .pe domain for 1 year included',
      'Cover design for your Google profile',
      'Email forwarding: messages sent to yourbusiness@mydomain.pe are forwarded to your Gmail (no extra cost)',
    ],
    ctaEs: 'Habla conmigo por WhatsApp ahora',
    ctaEn: 'Chat with me on WhatsApp now',
    forWhoEs: 'Ideal para: negocios que todavía no tienen presencia digital clara.',
    forWhoEn: 'Best for: businesses that still lack a clear digital presence.',
  },
  {
    planKey: 'landing-whatsapp',
    icon: 'zap',
    order: 1,
    popular: false,
    nameEs: 'Landing que vende por WhatsApp',
    nameEn: 'WhatsApp Sales Landing',
    price: 'S/ 399',
    priceNoteEs: 'Pago único',
    priceNoteEn: 'One-time payment',
    descriptionEs: 'Convierte tus anuncios de Facebook e Instagram en ventas reales por WhatsApp.',
    descriptionEn: 'Turn your Facebook and Instagram ads into real WhatsApp sales.',
    itemsEs: [
      'Botón de WhatsApp flotante',
      'Pixel de Facebook instalado y configurado',
      'Formulario simple de contacto',
      'Dominio .com.pe o .pe por 1 año incluido',
      'Seguimiento de 30 días (clics y mensajes)',
      'Correo profesional: info@tunegocio.pe',
    ],
    itemsEn: [
      'Floating WhatsApp button',
      'Facebook Pixel installed and configured',
      'Simple contact form',
      '.com.pe or .pe domain for 1 year included',
      '30-day tracking (clicks and messages)',
      'Professional email: info@yourbusiness.pe',
    ],
    ctaEs: 'Quiero mi web lista para vender',
    ctaEn: 'I want my web ready to sell',
    forWhoEs: 'Ideal para: negocios que invierten en Facebook o Instagram y quieren convertir mejor.',
    forWhoEn: 'Best for: businesses investing in Facebook or Instagram and wanting better conversions.',
  },
  {
    planKey: 'web-que-yo-edito',
    icon: 'star',
    order: 2,
    popular: false,
    nameEs: 'Web que yo mismo edito',
    nameEn: 'Website I Can Edit',
    price: 'S/ 599',
    priceNoteEs: 'Único + S/ 19/mes',
    priceNoteEn: 'One-time + S/ 19/mo',
    descriptionEs: 'Tu web de 3 páginas con panel sencillo. Cambias horarios, fotos y promos sin pedir ayuda.',
    descriptionEn: 'A 3-page website with a simple panel. Update hours, photos, and promos without asking for help.',
    itemsEs: [
      '3 páginas: Inicio, Servicios, Contacto',
      'Panel de edición en español (sin saber programación)',
      'Dominio .com.pe o .pe por 1 año incluido',
      '1 correo corporativo',
      'Cambia textos, fotos y promos tú mismo',
      'Soporte técnico incluido en la mensualidad',
    ],
    itemsEn: [
      '3 pages: Home, Services, Contact',
      'Spanish editing panel (no coding knowledge needed)',
      '.com.pe or .pe domain for 1 year included',
      '1 corporate email',
      'Update texts, photos and promos yourself',
      'Technical support included in the monthly fee',
    ],
    ctaEs: 'Quiero autonomía',
    ctaEn: 'I want autonomy',
    forWhoEs: 'Ideal para: dueños que quieren manejar su web sin depender de nadie.',
    forWhoEn: 'Best for: owners who want to manage their site without depending on anyone.',
  },
  {
    planKey: 'sueno-digital-completo',
    icon: 'sparkles',
    order: 3,
    popular: true,
    nameEs: 'Sueño Digital Completo',
    nameEn: 'Complete Digital Dream',
    price: 'S/ 999',
    priceNoteEs: 'Único + S/ 39/mes',
    priceNoteEn: 'One-time + S/ 39/mo',
    descriptionEs: 'Todo lo que necesita un negocio establecido. Web, blog, correos, dominio, soporte y backups.',
    descriptionEn: 'Everything an established business needs. Website, blog, emails, domain, support, and backups.',
    itemsEs: [
      'Web corporativa completa + Blog',
      'Dominio .pe o .com.pe incluido por 1 año',
      '3 correos corporativos (@tudominio)',
      'Backups diarios',
      'Informe mensual de rendimiento (visitas, clics, origen)',
      '3 horas de cambios gratis al mes',
      'Soporte prioritario por WhatsApp',
    ],
    itemsEn: [
      'Full corporate website + Blog',
      '.pe or .com.pe domain included for 1 year',
      '3 corporate emails (@yourdomain)',
      'Daily backups',
      'Monthly performance report (visits, clicks, source)',
      '3 free change hours per month',
      'Priority WhatsApp support',
    ],
    ctaEs: 'Quiero el paquete completo',
    ctaEn: 'I want the full package',
    forWhoEs: 'Ideal para: negocios establecidos que quieren todo listo y funcionando.',
    forWhoEn: 'Best for: established businesses that want everything ready and running.',
  },
  {
    planKey: 'mantenimiento-web',
    icon: 'star',
    order: 4,
    popular: false,
    nameEs: 'Mantenimiento Web Perú',
    nameEn: 'Website Maintenance Peru',
    price: 'S/ 79 – S/ 149',
    priceNoteEs: 'Por mes',
    priceNoteEn: 'Per month',
    descriptionEs: 'Olvídate de tu web. La mantenemos viva, segura y actualizada.',
    descriptionEn: 'Forget about your website. We keep it alive, secure, and updated.',
    itemsEs: [
      'Copias de seguridad mensuales',
      'Hasta 2 cambios de textos o fotos al mes (plan básico)',
      'Monitoreo de caídas 24/7',
      'Respuesta garantizada en menos de 4 horas (días hábiles)',
      'Reporte mensual de estado',
      'Gestión de renovación de dominio (tú solo pagas el costo)',
    ],
    itemsEn: [
      'Monthly backups',
      'Up to 2 text or photo updates per month (basic plan)',
      '24/7 uptime monitoring',
      'Guaranteed response in under 4 hours (business days)',
      'Monthly status report',
      'Domain renewal management (you only pay the fee)',
    ],
    ctaEs: 'Protege tu web ahora',
    ctaEn: 'Protect my website now',
    forWhoEs: 'Ideal para: negocios que ya tienen web pero no tienen tiempo de mantenerla.',
    forWhoEn: 'Best for: businesses that already have a website but no time to maintain it.',
  },
  {
    planKey: 'solo-dominio-correos',
    icon: 'star',
    order: 5,
    popular: false,
    nameEs: 'Solo dominio + correos',
    nameEn: 'Domain + Email Only',
    price: 'S/ 150',
    priceNoteEs: 'Por año',
    priceNoteEn: 'Per year',
    descriptionEs: 'Ya tienes web en otra plataforma (Wix, WordPress, etc.). Aquí te proporcionamos dominio propio y correos profesionales con tu marca.',
    descriptionEn: 'You already have a website on another platform (Wix, WordPress, etc.). Get your own domain and professional email with your brand.',
    itemsEs: [
      'Dominio .pe o .com.pe (el que tú elijas)',
      'Redirección de correos: lo que llegue a @tudominio se reenvía a tu Gmail personal',
      'Gestión completa del dominio por nosotros',
      'Renovación anual del dominio incluida en el precio',
      'Soporte técnico para configuración de correos',
      'Sin costo de hosting adicional (tu web sigue donde está)',
    ],
    itemsEn: [
      '.pe or .com.pe domain (your choice)',
      'Email forwarding: anything sent to @yourdomain gets forwarded to your personal Gmail',
      'Full domain management by us',
      'Annual domain renewal included in the price',
      'Technical support for email setup',
      'No additional hosting cost (your website stays where it is)',
    ],
    ctaEs: 'Agenda una llamada',
    ctaEn: 'Schedule a call',
    forWhoEs: 'Ideal para: negocios que ya tienen web pero quieren profesionalismo con dominio y correos propios.'
    forWhoEn: 'Best for: businesses that already have a website but want professionalism with their own domain and emails.',
  },
];

const SITE_SETTINGS_SEED = [
  { key: 'hero.badgeEs', value: 'Desarrollo Web Premium' },
  { key: 'hero.badgeEn', value: 'Premium Web Development' },
  { key: 'hero.titleEs', value: 'Construyo software que vende y escala' },
  { key: 'hero.titleEn', value: 'I build software that sells and scales' },
  { key: 'hero.subtitleEs', value: 'Landing pages, sitios corporativos y sistemas a medida orientados a conversiones.' },
  { key: 'hero.subtitleEn', value: 'Landing pages, corporate websites, and custom systems focused on conversions.' },
  { key: 'contact.email', value: 'contacto@gargurevichdigital.com' },
  { key: 'contact.whatsapp', value: '+51 966 918 363' },
  { key: 'contact.location', value: 'Lima, Peru' },
  { key: 'stats.projects', value: '50+' },
  { key: 'stats.clients', value: '100%' },
  { key: 'stats.experience', value: '3+' },
];

export async function POST() {
  try {
    // Upsert portfolio projects
    for (const p of PORTFOLIO_SEED) {
      await db.portfolioProject.upsert({
        where: { slug: p.slug },
        update: {},
        create: p,
      });
    }

    // Upsert services
    for (const s of SERVICES_SEED) {
      await db.service.upsert({
        where: { slug: s.slug },
        update: {},
        create: s,
      });
    }

    // Clear and re-seed offers (ensures old plans are replaced)
    await db.offer.deleteMany({});
    for (const o of OFFERS_SEED) {
      await db.offer.create({ data: o });
    }

    // Upsert site settings
    for (const s of SITE_SETTINGS_SEED) {
      await db.siteSetting.upsert({
        where: { key: s.key },
        update: {},
        create: s,
      });
    }

    revalidatePath('/', 'layout');

    return NextResponse.json({ ok: true, message: 'Database seeded successfully' });
  } catch (err) {
    console.error('Seed error:', err);
    return NextResponse.json({ error: 'Seed failed', detail: String(err) }, { status: 500 });
  }
}
